### PR TITLE
update path for zip extension file 

### PR DESCRIPTION
**Pull request by kernel-loophole**

### CODE REVIEW

**Comment by posix4e** [comment]
Please get rid of excess changes and commented out lines . Why do you cd surely that will break other stuff

**Review by posix4e — CHANGES_REQUESTED** [review]
Heck comments

**Comment by kernel-loophole** [comment]
i tried without cd  and  directly zip the files ,then it will create a empty zip file .

**Comment by posix4e** [comment]
Maybe spend a bit more time working on it, and see if that’s the only way
if nothing else you could use ( ) to make sure that it won’t effect later
commands

**Comment by kernel-loophole** [comment]
okay ,i will do.also test on your side and let me know if it work as required .

**Pull request closed without merging**
