### PR TITLE
tests for chrome extension

### PR DESCRIPTION
**Pull request by kernel-loophole**
This pull request addresses the addition of a new test case for the Chrome extension. The test case is designed to ensure the stability and functionality of the extension under specific conditions.
those tests are written using jasmine .
Added a new test case in the "spec" directory.
Added necessary test data and assertions to verify the expected behavior.

### CODE REVIEW

**Comment by posix4e** [comment]
1) Remove any hardcoded libraries, like jasmine
2) make sure all the images use git ifs
3) I removed the license files. Please be more careful
4) Make sure tests pass

**Comment by kernel-loophole** [comment]
Remove Jasmine Files may cause the dependencies  failure .Running Spec depend on the Jasmine  module and inside working directory the paths are defined specifically for that files.but let me try this .let you know if it work or not .

**Comment by posix4e** [comment]
It’s not an option. If you must modify the build to pull it down that’s
fine. But no checking it in

**Comment by kernel-loophole** [comment]
okay i will update the repo and remove the hard-coded files  after i test the extension.

**Pull request closed without merging**
