### PR TITLE
Llm adblock

### PR DESCRIPTION
**Pull request by urbit-pilled**
This PR implements LLM based by using VPNservice to allow or block on the domain level.
It works by intercepting packets on the android phone using a local VPN and sending a POST request to the puppet backend (/adblock_filter endpoint) with the domain name, the puppet backend then uses the LLM and responds with a JSON object 
```json
{"data":[{"allow":false,"full_response":"no the domain ads.google.com should not be allowed","error":null}],"is_generating":false,"duration":5.0021200180053710938,"average_duration":5.5438201588171499746}
```

The json is then parsed by the android app and then the network request is either blocked or allowed.

### CODE REVIEW

**Comment by urbit-pilled** [comment]
solves #35

**Comment by posix4e** [comment]
@urbit-pilled can you rebase and squash the fixes into the previous commits?

**Comment by urbit-pilled** [comment]
rebased back to second commit on this PR, is this fine, or do you want me to squash back to the first?

**Comment by posix4e** [comment]
rebase/squash is already better unless breaking it into different commits makes it more clear

**Comment by posix4e** [comment]
@urbit-pilled it would be great if you could add a test

**Pull request closed without merging**
