### PR TITLE
update cd with spirit File 

### PR DESCRIPTION
**Pull request by kernel-loophole**

### CODE REVIEW

**Review by posix4e — CHANGES_REQUESTED** [review]
You are confused. One file should just be for the tests. One file should just be for the release

**Comment by kernel-loophole** [comment]
so should I include my release code in this file https://github.com/posix4e/puppet/blob/main/.github/workflows/release_ci.yml

**Comment by kernel-loophole** [comment]
Also I have make sprit file for cd and test.

**Comment by posix4e** [comment]
I'm just going to do it myself

**Comment by kernel-loophole** [comment]
Okay thanks

**Pull request merged**
